### ISSUE TITLE
`npm run typecheck` does not works

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-hub/starter#3]
Hello,

I was trying the command `npm run typecheck` on this repo but it raises this error:

```
error TS5090: Non-relative paths are not allowed when 'baseUrl' is not set. Did you forget a leading './'?


Found 1 error.


[11:27:30 AM]  ERROR  Command failed with exit code 2: /home/esteban/dev/r/hub-starter-typecheck/node_modules/.pnpm/vue-tsc@2.0.16_typescript@5.4.5/node_modules/vue-tsc/bin/vue-tsc.js --noEmit

  at makeError (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/index3.mjs:1272:11)
  at handlePromise (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/index3.mjs:2510:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/typecheck.mjs:76:7)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7)



[11:27:30 AM]  ERROR  Command failed with exit code 2: /home/esteban/dev/r/hub-starter-typecheck/node_modules/.pnpm/vue-tsc@2.0.16_typescript@5.4.5/node_modules/vue-tsc/bin/vue-tsc.js --noEmit
```

I try to update deps and prepare the repo but nothing works.

**Comment by RihanArfan** [comment]
Hello 🙂 Thanks for reporting the issue! I created a new project to test this and I can't seem to replicate the issue anymore, so it may have been solved in a release since the issue was opened.

```bash
pnpx nuxthub init starter-3-testing
cd starter-3-testing/
pnpm add -D vue-tsc typescript
pnpx nuxi typecheck
```

Let me know if that's not the case and I'll dig into it more

**Comment by Barbapapazes** [comment]
It seems to be working now! 🙌
